# Generated by Django 3.1 on 2020-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=20)),
                ('Marks', models.IntegerField()),
            ],
        ),
    ]
