# Generated by Django 3.1 on 2020-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200807_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
