# Generated by Django 3.1 on 2020-08-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200807_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Role',
            field=models.CharField(default='User', max_length=10),
            preserve_default=False,
        ),
    ]
