# Generated by Django 3.1 on 2020-08-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Role',
            new_name='Roles',
        ),
    ]
