# Generated by Django 3.1 on 2020-08-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0002_auto_20200810_2230'),
        ('Users', '0005_auto_20200810_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Role.role'),
        ),
    ]
