# Generated by Django 3.1 on 2020-08-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0004_auto_20200817_1326'),
        ('Users', '0006_auto_20200810_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Roles',
            field=models.ForeignKey(db_column='Role.Role_name', on_delete=django.db.models.deletion.CASCADE, to='Role.role'),
        ),
    ]
