# Generated by Django 3.1 on 2020-08-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0004_auto_20200817_1326'),
        ('Users', '0010_auto_20200818_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Role.role', to_field='Role_name'),
        ),
    ]
