# Generated by Django 3.1 on 2020-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role_Id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Role_name', models.CharField(max_length=100)),
            ],
        ),
    ]
