# Generated by Django 3.1 on 2020-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Role_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
