# Generated by Django 3.1 on 2020-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0002_auto_20200810_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Role_Id',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='Role_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
