# Generated by Django 3.1 on 2020-08-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0003_auto_20200817_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Role_Id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='Role_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
