# Generated by Django 3.1 on 2020-08-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=500, unique=True)),
                ('Option_A', models.CharField(max_length=200)),
                ('Option_B', models.CharField(max_length=200)),
                ('Option_C', models.CharField(max_length=200)),
                ('Option_D', models.CharField(max_length=200)),
                ('Answers', models.CharField(max_length=200)),
            ],
        ),
    ]
